In [1]:
import numpy as np

# Вектор

## Вектор-строка

In [2]:
v_hor_np = np.array([1, 2])
print(v_hor_np )

[1 2]


In [3]:
v_hor_zeros_v1 = np.zeros((5,))
print(v_hor_zeros_v1 )

[0. 0. 0. 0. 0.]


In [4]:
v_hor_zeros_v2 = np.zeros((1, 5))
print(v_hor_zeros_v2 )

[[0. 0. 0. 0. 0.]]


In [5]:
v_hor_one_v1 = np.ones((5,))
print(v_hor_one_v1)
v_hor_one_v2 = np.ones((1, 5))
print(v_hor_one_v2)

[1. 1. 1. 1. 1.]
[[1. 1. 1. 1. 1.]]


## Вектор-столбец

In [6]:
v_vert_np = np.array([[1], [2]])
print(v_vert_np)

[[1]
 [2]]


In [7]:
v_vert_zeros = np.zeros((5, 1))
print(v_vert_zeros)

[[0.]
 [0.]
 [0.]
 [0.]
 [0.]]


In [8]:
v_vert_ones = np.ones((5, 1))
print(v_vert_ones)

[[1.]
 [1.]
 [1.]
 [1.]
 [1.]]


# Квадратная матрица

In [9]:
m_sqr_arr = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
print(m_sqr_arr)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [10]:
m_sqr = [[1, 2, 3], [4, 5, 6], [7, 8, 9]]
m_sqr_arr = np.array(m_sqr)
print(m_sqr_arr)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [11]:
m_sqr_mx = np.matrix([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
print(m_sqr_mx)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [12]:
m_sqr_mx = np.matrix('1 2 3; 4 5 6; 7 8 9')
print(m_sqr_mx)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


# Диагональная матрица

In [13]:
m_diag = [[1, 0, 0], [0, 5, 0], [0, 0, 9]]
m_diag_np = np.matrix(m_diag)
print(m_diag_np)

[[1 0 0]
 [0 5 0]
 [0 0 9]]


In [14]:
m_sqr_mx = np.matrix('1 2 3; 4 5 6; 7 8 9')
diag = np.diag(m_sqr_mx)
print(diag)

[1 5 9]


In [15]:
m_diag_np = np.diag(np.diag(m_sqr_mx))
print(m_diag_np)

[[1 0 0]
 [0 5 0]
 [0 0 9]]


# Единичная матрица

In [16]:
m_e = [[1, 0, 0], [0, 1, 0], [0, 0, 1]]
m_e_np = np.matrix(m_e)
print(m_e_np)

[[1 0 0]
 [0 1 0]
 [0 0 1]]


In [17]:
m_eye = np.eye(3)
print(m_eye)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [18]:
m_idnt = np.identity(3)
print(m_idnt)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


# Нулевая матрица

In [19]:
m_zeros = np.zeros((3, 3))
print(m_zeros)

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


# Задание матрицы в общем виде

In [20]:
m_mx = np.matrix('1 2 3; 4 5 6')
print(m_mx)

[[1 2 3]
 [4 5 6]]


# Транспонирование матрицы

In [21]:
A = np.matrix('1 2 3; 4 5 6')
print(A)

[[1 2 3]
 [4 5 6]]


In [22]:
A_t = A.transpose()
print(A_t)

[[1 4]
 [2 5]
 [3 6]]


In [23]:
print(A.T)

[[1 4]
 [2 5]
 [3 6]]


# Действия над матрицами

## Умножение матрицы на число

In [24]:
A = np.matrix('1 2 3; 4 5 6')
C = 3 * A
print(C)

[[ 3  6  9]
 [12 15 18]]


## Сложение матриц

In [25]:
A = np.matrix('1 6 3; 8 2 7')
B = np.matrix('8 1 5; 6 9 12')
C = A + B
print(C)

[[ 9  7  8]
 [14 11 19]]


## Умножение матриц

In [26]:
A = np.matrix('1 2 3; 4 5 6')
B = np.matrix('7 8; 9 1; 2 3')
C = A.dot(B)
print(C)

[[31 19]
 [85 55]]


## Определитель матрицы

In [27]:
A = np.matrix('-4 -1 2; 10 4 -1; 8 3 1')
print(A)

[[-4 -1  2]
 [10  4 -1]
 [ 8  3  1]]


In [28]:
np.linalg.det(A)

-14.000000000000009

## Обратная матрица

In [29]:
A = np.matrix('1 -3; 2 5')
A_inv = np.linalg.inv(A)
print(A_inv)

[[ 0.45454545  0.27272727]
 [-0.18181818  0.09090909]]


# Ранг матрицы

In [30]:
m_eye = np.eye(4)
print(m_eye)

[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]


In [31]:
rank = np.linalg.matrix_rank(m_eye)
print(rank)

4
